const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

export const CHECK_SCHMEA_REQUEST = "CHECK_SCHMEA_REQUEST";
export const CHECK_SCHMEA_SUCCESS = "CHECK_SCHMEA_SUCCESS";
export const CHECK_SCHMEA_FAILURE = "CHECK_SCHMEA_FAILURE";
export const RESET_STATE = "RESET_STATE";

export const CREATE_SCHEMA_REQUEST = "CREATE_SCHEMA_REQUEST";
export const CREATE_SCHEMA_SUCCESS = "CREATE_SCHEMA_SUCCESS";
export const CREATE_SCHEMA_FAILURE = "CREATE_SCHEMA_FAILURE";

export const INSERT_RECORD_REQUEST = "INSERT_RECORD_REQUEST";
export const INSERT_RECORD_SUCCESS = "INSERT_RECORD_SUCCESS";
export const INSERT_RECORD_FAILURE = "INSERT_RECORD_FAILURE";

export const ANCHOR_LIST_REQUEST = "ANCHOR_LIST_REQUEST";
export const ANCHOR_LIST_SUCCESS = "ANCHOR_LIST_SUCCESS";
export const ANCHOR_LIST_FAILURE = "ANCHOR_LIST_FAILURE";

export {
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILURE,
  USER_LOGOUT_REQUEST,
  USER_LOGOUT_SUCCESS,
  USER_LOGOUT_FAILURE,
};
